# Generated by Django 5.1.1 on 2024-09-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_rename_user_comment_author_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/anime.png', upload_to='post_images/'),
        ),
    ]
