# Generated by Django 5.1.1 on 2024-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_course_courseresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='is_unsafe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='courseresource',
            unique_together={('course', 'name')},
        ),
    ]
