# Generated by Django 5.1.1 on 2024-12-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0011_blockeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
